name: Build

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Gradle
      run: ./gradlew build '-Pversion=${{ github.run_number }}'
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: CodeUtilities
        path: ./build/libs/CodeUtilities*.jar
    - name: Publish Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ github.run_number }}"
        prerelease: false
        files: |
          LICENSE.txt
          ./build/libs/CodeUtilities-${{ github.run_number }}.jar
