name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: CodeUtilities
        path: ./build/libs/CodeUtilities-[0-9].[0-9].[0-9].jar
    - name: Alert Discord
      uses: fjogeleit/http-request-action@master
      with:
        url: '${{ secrets.UPDATE_ALERT }}'
        method: 'GET' 
